
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EQUALS FLOAT INT MINUS MULTIPLY NAME PLUS\n    calc : expression \n            | empty\n    \n    expression : expression MULTIPLY expression\n                | expression DIVIDE expression\n                | expression PLUS expression\n                | expression MINUS expression\n                \n    \n    expression : INT \n                | FLOAT \n    \n    empty :\n    '
    
_lr_action_items = {'DIVIDE':([1,2,4,10,11,12,13,],[-7,-8,8,8,8,8,8,]),'INT':([0,6,7,8,9,],[1,1,1,1,1,]),'FLOAT':([0,6,7,8,9,],[2,2,2,2,2,]),'PLUS':([1,2,4,10,11,12,13,],[-7,-8,7,7,7,7,7,]),'MULTIPLY':([1,2,4,10,11,12,13,],[-7,-8,6,6,6,6,6,]),'MINUS':([1,2,4,10,11,12,13,],[-7,-8,9,9,9,9,9,]),'$end':([0,1,2,3,4,5,10,11,12,13,],[-9,-7,-8,0,-1,-2,-3,-5,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[3,]),'expression':([0,6,7,8,9,],[4,10,11,12,13,]),'empty':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> expression','calc',1,'p_calc','calc.py',48),
  ('calc -> empty','calc',1,'p_calc','calc.py',49),
  ('expression -> expression MULTIPLY expression','expression',3,'p_expression','calc.py',55),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','calc.py',56),
  ('expression -> expression PLUS expression','expression',3,'p_expression','calc.py',57),
  ('expression -> expression MINUS expression','expression',3,'p_expression','calc.py',58),
  ('expression -> INT','expression',1,'p_expression_int_float','calc.py',65),
  ('expression -> FLOAT','expression',1,'p_expression_int_float','calc.py',66),
  ('empty -> <empty>','empty',0,'p_empty','calc.py',72),
]
